coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      behavior:
        target: 80%
        threshold: 0%
        informational: true
        only_pulls: true
        paths:
          - "server/src/main/kotlin"
          - "!server/src/main/kotlin/com/plainbase/Application.kt"
          - "!server/src/main/kotlin/com/plainbase/frameworks/ktor/KtorServer.kt"

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
