coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        removed_code_behavior: adjust_base
    patch:
      behavior:
        target: 80%
        threshold: 0%
        informational: true
        only_pulls: true
        paths:
          - "server/src/main/kotlin"
          - "!server/src/main/kotlin/com/plainbase/Application.kt"
          - "!server/src/main/kotlin/com/plainbase/frameworks/ktor/KtorServer.kt"

ignore:
  - "server/build/generated/sqldelight/**"
  - "server/src/main/kotlin/com/plainbase/Application.kt"

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: "coverage_drop OR uncovered_patch"
  require_base: true
  require_head: true
  hide_project_coverage: false
