import { mkdirSync } from "node:fs";
import path from "node:path";
import { expect, test } from "./smoke-fixtures";
import { gotoExpectStatus } from "./helpers";

const PAGE = "/docs/scratch/todo";
test("search and link shortcuts have separate ownership without deleting source", async ({ page }) => {
  await gotoExpectStatus(page, `${PAGE}?mode=edit`);
  const content = page.locator(".cm-content");
  await expect(page.getByRole("status", { name: "Save state" })).toHaveText("Saved");
  const source = () => page.locator(".cm-line").evaluateAll((lines) => lines.map((line) => line.textContent).join("\n"));
  const original = await source();
  let puts = 0;
  page.on("request", (request) => { if (request.method() === "PUT") puts++; });
  await content.focus();
  await content.press("ControlOrMeta+End");
  await content.press("ControlOrMeta+k");
  await expect(page.getByRole("dialog", { name: "Search" })).toBeVisible();
  expect(await source()).toBe(original);
  await expect(page.getByRole("status", { name: "Save state" })).toHaveText("Saved");
  await page.keyboard.press("Escape");
  await expect(content).toBeFocused();
  await content.press("ControlOrMeta+Shift+k");
  await expect(page.getByRole("dialog", { name: "Search" })).toHaveCount(0);
  expect(await source()).toBe(`${original}[](url)`);
  await expect(page.getByRole("status", { name: "Save state" })).toHaveText("Unsaved changes");
  await content.press("ControlOrMeta+z");
  expect(await source()).toBe(original);
  expect(puts).toBe(0);
});

for (const theme of ["light", "dark"] as const) {
  test(`${theme} editor keeps one centered source with properties, diagnostics and Preview`, async ({ page, request }) => {
    await page.emulateMedia({ colorScheme: theme });
    await page.setViewportSize({ width: theme === "dark" ? 1440 : 1280, height: 1000 });
    const record = await (await request.get("/api/v1/pages/by-path/docs/scratch/todo")).json() as { id: string; content_hash: string };
    const prose = "Ordinary prose wraps comfortably without forcing the whole window to scroll. ".repeat(8);
    const table = `| Name | Description |\n| --- | --- |\n| Example | ${"Long table cell ".repeat(18)} |`;
    const buffer = `---\ntitle: Editor example\nstatus: draft\nowner: Ada Lovelace\n---\n# Editor example\n\n[Missing guide](missing-editor-guide.md)\n\n${prose}\n\n${table}\n\nA prose | pipe stays prose.\n\n\`\`\`text\n| fenced | content |\n\`\`\`\n`;
    const saved = await request.put(`/api/v1/pages/${record.id}?root=docs`, { headers: { "content-type": "text/markdown", "if-match": `"${record.content_hash}"` }, data: buffer });
    expect(saved.ok(), await saved.text()).toBe(true);
    let puts = 0;
    page.on("request", (req) => { if (req.method() === "PUT") puts++; });
    await gotoExpectStatus(page, `${PAGE}?mode=edit`);
    const editor = page.locator("[data-pb-editor]");
    await expect(editor.getByRole("status", { name: "Save state" })).toHaveText("Saved");
    const mark = page.getByRole("button", { name: "Broken link: missing-editor-guide.md" });
    await expect(mark).toBeVisible();
    await mark.focus(); await page.keyboard.press("Enter");
    await expect(page.locator(".cm-content")).toBeFocused();
    expect(await page.evaluate(() => window.getSelection()?.anchorNode?.parentElement?.closest(".cm-line")?.textContent)).toContain("Missing guide");
    await expect(page.locator(".cm-lineNumbers")).toBeVisible();
    expect((await editor.boundingBox())!.width).toBeLessThanOrEqual(960);
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    const rows = page.locator(".pb-editor-table-line");
    await expect(rows).toHaveCount(3);
    for (const row of await rows.all()) expect(await row.evaluate((node) => getComputedStyle(node).whiteSpace)).toBe("pre");
    await expect(page.locator('.cm-line').filter({ hasText: "A prose | pipe" })).not.toHaveClass(/pb-editor-table-line/);
    await expect(page.locator('.cm-line').filter({ hasText: "| fenced | content |" })).not.toHaveClass(/pb-editor-table-line/);
    expect(await page.locator(".cm-scroller").evaluate((node) => node.scrollWidth > node.clientWidth)).toBe(true);
    const proseGeometry = await page.locator(".cm-line").filter({ hasText: "Ordinary prose wraps" }).evaluate((node) => ({ width: node.getBoundingClientRect().width, viewport: node.closest(".cm-scroller")!.clientWidth }));
    expect(proseGeometry.width).toBeLessThan(proseGeometry.viewport);
    const shots = path.resolve("../.crew/ui-editor-screenshots"); mkdirSync(shots, { recursive: true });
    await page.screenshot({ path: path.join(shots, `${theme}-write.png`), fullPage: true });
    const owner = page.locator(".pb-editor-property summary").filter({ hasText: "Owner" });
    await owner.click();
    await expect(page.getByRole("textbox", { name: "Owner", exact: true })).toBeVisible();
    await page.screenshot({ path: path.join(shots, `${theme}-property.png`), fullPage: true });
    await page.getByRole("textbox", { name: "Owner", exact: true }).focus();
    await page.keyboard.press("Escape"); await expect(owner).toBeFocused();
    const scroller = page.locator(".cm-scroller");
    const scroll = await scroller.evaluate((node) => { node.scrollLeft = 180; return node.scrollLeft; });
    expect(scroll).toBeGreaterThan(0);
    await editor.getByRole("button", { name: "Preview", exact: true }).click();
    await expect(page.locator("[data-pb-preview] .pb-prose")).toContainText("Editor example");
    await expect(page.locator("[data-pb-fmt-bold]")).toBeDisabled();
    expect(await page.locator(".cm-content").evaluate((node) => !!node.closest("[inert]"))).toBe(true);
    await page.screenshot({ path: path.join(shots, `${theme}-preview.png`), fullPage: true });
    await editor.getByRole("button", { name: "Write", exact: true }).click();
    expect(await scroller.evaluate((node) => node.scrollLeft)).toBe(scroll);
    const content = page.locator(".cm-content");
    await expect(content).toBeFocused();
    await content.press("ControlOrMeta+End"); await page.keyboard.insertText("\nUnsaved marker");
    await expect(editor.getByRole("status", { name: "Save state" })).toHaveText("Unsaved changes");
    await expect(mark).toHaveCount(0);
    page.once("dialog", (dialog) => dialog.accept());
    await editor.getByRole("button", { name: "Discard", exact: true }).click();
    await expect(content).not.toContainText("Unsaved marker");
    expect(puts).toBe(0);
    await content.focus(); await content.press("ControlOrMeta+End"); await page.keyboard.insertText("\nSaved shortcut marker");
    await content.press("ControlOrMeta+s");
    await expect(editor.getByRole("status", { name: "Save state" })).toHaveText("Saved");
    expect(puts).toBe(1);
    const after = await (await request.get(`/api/v1/pages/${record.id}?root=docs`)).json() as { markdown: string };
    expect(after.markdown).toContain("Saved shortcut marker");
  });
}

test("table layout reaches a later viewport without treating pipe prose as a table", async ({ page }) => {
  await gotoExpectStatus(page, `${PAGE}?mode=edit`);
  const content = page.locator(".cm-content");
  await content.focus(); await content.press("ControlOrMeta+a");
  await page.keyboard.insertText(Array.from({ length: 700 }, (_, i) => `Paragraph ${i} with a | prose pipe.\n\n`).join("") + "| Later | Table |\n| --- | --- |\n| End | Cell |\n");
  await content.press("ControlOrMeta+End");
  await expect(page.locator(".pb-editor-table-line").filter({ hasText: "Later" })).toBeVisible();
  expect(await page.locator(".pb-editor-table-line").filter({ hasText: "Later" }).evaluate((node) => getComputedStyle(node).whiteSpace)).toBe("pre");
  await expect(page.locator(".pb-editor-table-line").filter({ hasText: "prose pipe" })).toHaveCount(0);
});

test("Write diagnostics parse preview resources inertly", async ({ page }) => {
  const loaded: string[] = [];
  page.on("request", (request) => { if (request.url().includes("diagnostic-resource-probe")) loaded.push(request.url()); });
  await page.route("**/api/v1/preview?*", (route) => route.fulfill({ json: { html: '<img src="/diagnostic-resource-probe.png"><span data-pb-link-error="not_found" data-pb-link-src="0-1" data-pb-link-target="missing.md">x</span>', headings: [] } }));
  await gotoExpectStatus(page, `${PAGE}?mode=edit`);
  await expect(page.getByRole("button", { name: "Broken link: missing.md" })).toBeVisible();
  await page.locator(".cm-content").focus();
  await page.keyboard.insertText("More");
  await expect(page.getByRole("status", { name: "Link checks" })).toHaveText("1 line needs attention");
  expect(loaded).toEqual([]);
  await expect(page.locator("[data-pb-preview]")).toHaveCount(0);
});
